/**
 * The app mark, in one place.
 *
 * The icon files are generated by `brand/build-icons.py`, which is Python and
 * cannot import this module. So the Riyal glyph exists twice: once there, once
 * here for anything the app renders at runtime. `scripts/verify-brand-sync.mjs`
 * asserts the two copies still agree, and runs as part of `npm run test:ui` —
 * if you edit one, the test tells you about the other rather than letting the
 * loader drift away from the favicon.
 */

/**
 * The Saudi Riyal symbol published by SAMA in 2025, as two paths in a
 * 1124.14 x 1256.39 box with the origin at top-left. Copied verbatim from
 * brand/Saudi_Riyal_Symbol.svg; only fill and transform are ever applied.
 */
export const RIYAL_PATHS = [
  "M699.62,1113.02h0c-20.06,44.48-33.32,92.75-38.4,143.37l424.51-90.24c20.06-44.47," +
    "33.31-92.75,38.4-143.37l-424.51,90.24Z",
  "M1085.73,895.8c20.06-44.47,33.32-92.75,38.4-143.37l-330.68,70.33v-135.2l292.27-62.11" +
    "c20.06-44.47,33.32-92.75,38.4-143.37l-330.68,70.27V66.13c-50.67,28.45-95.67,66.32-132.25," +
    "110.99v403.35l-132.25,28.11V0c-50.67,28.44-95.67,66.32-132.25,110.99v525.69l-295.91,62.88" +
    "c-20.06,44.47-33.33,92.75-38.42,143.37l334.33-71.05v170.26l-358.3,76.14c-20.06,44.47-33.32," +
    "92.75-38.4,143.37l375.04-79.7c30.53-6.35,56.77-24.4,73.83-49.24l68.78-101.97v-.02c7.14-10.55," +
    "11.3-23.27,11.3-36.97v-149.98l132.25-28.11v270.4l424.53-90.28Z",
] as const;

export const RIYAL_VIEWBOX = { width: 1124.14, height: 1256.39 } as const;

/**
 * Credit and debit colours, matching the `emerald-400` and `rose-400` already
 * used for amounts throughout the UI. Hard-coded rather than pulled from
 * Tailwind because the icon build needs the same two values and reads them
 * from the Python side.
 */
export const BRAND = {
  credit: "#34D399",
  debit: "#FB7185",
} as const;
