-- Editable accounts, with the edit written down (SPEC §3.3b, §9.4, §12.7).
--
-- Two additions, for one feature:
--
--   `adjustment` — a transaction type for a balance corrected by hand. It has
--   to be a transaction rather than an UPDATE on accounts.current_balance,
--   because `recompute_balances` (api/db.py) derives every balance as
--   opening_balance + Σ(posted legs) on every tick. A written balance is gone
--   within the minute; a booked one is part of the sum that replaces it, and
--   survives replay because origin='manual' is never touched (§9.4).
--
--   `account_edits` — one row per save, naming the fields that moved. An
--   account holds the numbers net worth is computed from, and §3.3a is a
--   14,000 error from one of them being read the wrong way round; changing
--   those silently is not something a ledger gets to offer.
--
-- Generated by drizzle-kit, then annotated and given the RLS statement below.
-- IF NOT EXISTS on the enum value so re-running against a database that
-- already has it is a no-op rather than a failed migration.

ALTER TYPE "public"."transaction_type" ADD VALUE IF NOT EXISTS 'adjustment';--> statement-breakpoint
CREATE TABLE "account_edits" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"account_id" uuid NOT NULL,
	"changed" jsonb NOT NULL,
	"note" text,
	"adjustment_transaction_id" uuid,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
ALTER TABLE "account_edits" ADD CONSTRAINT "account_edits_account_id_accounts_id_fk" FOREIGN KEY ("account_id") REFERENCES "public"."accounts"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
-- The account goes, its edit history goes with it. The adjustment leg does
-- not: it is a real row in the ledger that a balance is derived from, so
-- deleting it would move that balance. The link is dropped instead.
ALTER TABLE "account_edits" ADD CONSTRAINT "account_edits_adjustment_transaction_id_transactions_id_fk" FOREIGN KEY ("adjustment_transaction_id") REFERENCES "public"."transactions"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "account_edits_account_idx" ON "account_edits" USING btree ("account_id","created_at");--> statement-breakpoint

-- Migration 0004 locked every table that existed then, and warned that the
-- next table created would otherwise be world-writable again over PostgREST.
-- This is that next table.
ALTER TABLE "account_edits" ENABLE ROW LEVEL SECURITY;
