"use server";

import { inArray } from "drizzle-orm";
import { revalidatePath } from "next/cache";

import { getDb, schema } from "@/db";

/**
 * Requeue a whole shape group (SPEC §10.7).
 *
 * The point of grouping: after adding a template for a format, one action
 * reprocesses every message that was parked waiting for it. Bank messages
 * repeat by nature, so a format you fix once should never cost you twice.
 *
 * `attempts` resets to zero because the previous failures were the system's
 * fault, not the message's — otherwise three old failures would park a
 * perfectly parseable message on its first retry.
 */
export async function retryGroup(ids: string[]) {
  if (ids.length === 0) return;

  const db = getDb();
  await db
    .update(schema.rawMessages)
    .set({ status: "pending", attempts: 0, lastError: null, processedAt: null })
    .where(inArray(schema.rawMessages.id, ids));

  revalidatePath("/review");
  revalidatePath("/");
}

/**
 * Mark a group as legitimately not-a-transaction.
 *
 * Sets status rather than deleting: raw_messages is append-only (§3.1), and a
 * message dismissed by mistake has to remain recoverable. `ignored_reason =
 * 'user'` distinguishes a human decision from an automatic OTP filter, so a
 * later classifier change can revisit these without second-guessing you.
 */
export async function dismissGroup(ids: string[]) {
  if (ids.length === 0) return;

  const db = getDb();
  await db
    .update(schema.rawMessages)
    .set({ status: "ignored", ignoredReason: "user", lastError: null })
    .where(inArray(schema.rawMessages.id, ids));

  revalidatePath("/review");
  revalidatePath("/");
}

export type DeriveResult = { ok: true; requeued: number } | { ok: false; error: string };

/**
 * Derive a template from a marked-up message (SPEC §10.7).
 *
 * Forwards to the parser service rather than deriving here. The regex has to
 * be written against the SAME normalized text the parser matches on, next to
 * the letterform folding and spacing rules that produced it. A second
 * implementation in TypeScript would agree right up until the day it didn't.
 */
export async function deriveTemplate(
  _prev: DeriveResult | null,
  form: FormData,
): Promise<DeriveResult> {
  const secret = process.env.INTERNAL_SECRET;
  // In production PARSER_URL is generated by the service binding in
  // vercel.json, not set by hand. Locally it comes from web/.env.local.
  // Trailing slash stripped because the two sources disagree about it and
  // `//api/...` is not reliably routed.
  const base = (process.env.PARSER_URL ?? "").replace(/\/+$/, "");
  if (!secret) return { ok: false, error: "INTERNAL_SECRET is not set in web/.env.local" };

  const str = (k: string) => (form.get(k) as string | null)?.trim() ?? "";

  // Only send fields that were actually filled in — an empty string would be
  // read as "this value appears in the message" and fail to locate.
  const fields: Record<string, string> = {};
  for (const name of ["amount", "balance", "fee_amount", "merchant", "counterparty",
                      "card", "from_account", "to_account", "biller", "date_raw"]) {
    const v = str(name);
    if (v) fields[name] = v;
  }

  let res: Response;
  try {
    res = await fetch(`${base}/api/templates/derive`, {
      method: "POST",
      headers: { "Content-Type": "application/json", "X-Internal-Secret": secret },
      body: JSON.stringify({
        message_id: str("message_id"),
        kind: str("kind"),
        direction: str("direction"),
        date_format: str("date_format") || null,
        account_hint: str("account_hint") || null,
        fields,
      }),
    });
  } catch {
    return {
      ok: false,
      error: `Can't reach the parser service at ${base || "(PARSER_URL unset)"}. Start it, or run both with \`vercel dev\`.`,
    };
  }

  if (!res.ok) {
    const body = await res.json().catch(() => null);
    // The service returns 422 with a specific reason when it refuses to store
    // a template it could not verify. That reason is the useful part.
    return { ok: false, error: body?.detail ?? `${res.status} ${res.statusText}` };
  }

  const body = await res.json();
  revalidatePath("/review");
  revalidatePath("/");
  return { ok: true, requeued: body.requeued ?? 0 };
}

/** Undo a dismissal — back into the queue for another look. */
export async function restoreGroup(ids: string[]) {
  if (ids.length === 0) return;

  const db = getDb();
  await db
    .update(schema.rawMessages)
    .set({ status: "pending", ignoredReason: null, attempts: 0, lastError: null })
    .where(inArray(schema.rawMessages.id, ids));

  revalidatePath("/review");
  revalidatePath("/");
}
